site_name: Quantman
theme:
  name: material
  favicon: assets/favicon.png

copyright: Copyright © 2021, Quantman. All rights reserved.
extra:
  generator: false
  social: 
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/quantman1
  - icon: fontawesome/brands/facebook
    link: https://www.facebook.com/quant.man.16/